# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token = 76fdf1aeee41d9b7f94fee54e7a51fa2cdba43f9

# получение объявлений 
# Для анонимов можно только 2 запроса в минуту, для авторизованных пользователей 10
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token}}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "ТЕСТОВОЕ 1-е",
  "description": "Срочно"
}

###
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "Тестовое 2-е",
  "description": "Срочно"
}

###

# попытка поменять объявление на статус CLOSED
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token {{token}}

{
  "status": "OPEN"
}

### попытка поменять объявление на статус OPEN

PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token {{token}}

{
  "status": "CLOSED"
}


### 
# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at=2024-05-14T08:03:52.164487Z
Content-Type: application/json
Authorization: Token {{token}}

###

# Фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json
Authorization: Token 76fdf1aeee41d9b7f94fee54e7a51fa2cdba43f9

### Удаление объявлений
DELETE  {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token {{token}}
